### PR TITLE
Add option for using MemAvailable instead of MemFree

### PR DESCRIPTION
**Pull request by martinwe-adfinis**
Add the `-a` option for letting the check use the `MemAvailable` for deciding whether or not to alert (instead of Used/Free). This currently only works on Linux (as it is unclear whether other OSes provide `MemAvailable`).

### CODE REVIEW

**Comment by martinwe-adfinis** [comment]
Note that `-a` will behave like `-f` (i.e. look at the *remaining* memory). Let me know if it should also allow checking `${total} - ${available}`.

Also, I'm not very well-versed in Perl, so this may be a little ham-fisted. Suggestions welcome!

Finally, I've added a check to only allow exactly one of `-u`, `-f` and `-a`. Let me know if I should split that into a separate commit.

**Comment by beatrubi** [comment]
Looks good to me, but please let `/usr/bin/perl` validate your code too :)

> it is unclear whether other OSes provide `MemAvailable`

As all those fancy proc files, meminfo is only available in Linux. `MemAvailable` was introduced a few years ago, we might see older installations lacking the variable.

**Comment by martinwe-adfinis** [comment]
I just noticed there was a minor logic error with calculating the thresholds for the metrics output (it's actually in the same case as `$arg_u` rather than `$arg_f`, which seems a little unintuitive at first, but only because we look at the *lower* threshold for AVAILABLE (whereas FREE and USED both translate to *upper* thresholds on the USED field)).

I've fixed that now, but do you want me to add a comment in the code to explain that, or is the logic self-explanatory?

**Comment by martinwe-adfinis** [comment]
Fixed another minor issue with the arguments checking (it would previously allow something like `-f -u` or any other two-options combinations, and only reject all three at once, but we want to ensure that only exactly one among `-f`, `-u` or `-a` is passed).

**Pull request merged**
