### PR TITLE
Support hugepages larger than 2MB

### PR DESCRIPTION
**Pull request by aieri**
The code currently looks into /proc/meminfo to determine how much memory is used for hugepages, but that interface only reports pages of size 2MB.
A newer sysfs interface is however available, and this PR implements reading from it instead.

### CODE REVIEW

**Comment by justintime** [comment]
Hey there, thanks for the contribution.

It looks as though your code will work fine on newer systems with the new sysfs support, but it looks like it will die() anytime it's run on older systems.  Can you make your changes be backwards compatible?  Basically, if the newer sysfs structure exists, but if it doesn't, fall back to the old method?

**Comment by aieri** [comment]
Good point, I didn't think about old linuxes... I'll update the code to fallback to /proc/sys/vm/nr_hugepages if /sys/kernel/mm/hugepages is unavailable.

**Comment by aieri** [comment]
I've basically revived the current version and chose to simply overwrite the hugepages counters if the newer sysfs interface is available

**Comment by justintime** [comment]
Looks good to me, thanks!

**Pull request merged**
